services:
  - type: web
    name: therapist-ai-backend
    env: docker
    region: frankfurt
    plan: free
    repo: https://github.com/NermeenKamal/Therapist-AI-MobileApp
    branch: main
    rootDir: Backend
    buildCommand: "docker build -t backend ."
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: 
      - key: APP_URL
        value: https://therapist-ai-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
