release: |
  php artisan config:clear
  php artisan route:clear
  php artisan view:clear
  php artisan cache:clear
  php artisan config:cache
  php artisan migrate --force
  php artisan queue:restart

web: php artisan serve --host=0.0.0.0 --port=${PORT}
worker: php artisan queue:work --tries=3 --timeout=60
